config/SuperBuild/CMakeLists.txt, config/SuperBuild/TPLVersions.cmake, config/SuperBuild/include/Build_HDF5.cmake
merged amanzi-ideas branch into alexis/xsdk-spack branch
=> Amanzi ideas

src/mesh/mesh_mstk/CMakeLists.txt, src/mesh/mesh_mstk/Mesh_MSTK.cc, src/mesh/mesh_mstk/test/test_nonmanifold_surfaces.cc
This adds a test to ensure that we can read and process a mesh/model of non-manifold surfaces (in this case two planar surfaces meeting at a right angle in 3-space).
=> Test for nonmanifold surfaces and small bug fix

README, README.md
Include a helpful status icon for Travis CI
=> Formatting updates to README

CMakeLists.txt, bootstrap.sh, config/SuperBuild/CMakeLists.txt, config/SuperBuild/TPLVersions.cmake, config/SuperBuild/templates/amanzi-tpl-config.cmake.in, config/SuperBuild/templates/netcdf-cmake-rpath.patch, config/SuperBuild/templates/netcdf-cmake.patch, src/executables/CMakeLists.txt, src/operators/PDE_AdvectionUpwind.hh, src/operators/ReconstructionCell.hh, src/pks/flow/CMakeLists.txt, src/pks/transport/test/transport_convergence.cc, tools/cmake/AmanziTPL.cmake, tools/cmake/Modules/FindBoost.cmake
Updated two TPLs to the most recent versions.
=> Upgraded HDF5 and NetCDF.

config/SuperBuild/TPLVersions.cmake
Updated one TPL, OpenMPI, to the recent version
=> Updated OpenMPI to 3.1.1

.travis.yml, config/SuperBuild/TPLVersions.cmake, src/geometry/RegionFactory.cc, src/mesh/mesh_logical/MeshLogical.cc, src/mesh/mesh_logical/MeshLogical.hh, src/mesh/mesh_logical/MeshLogicalFactory.cc, src/mesh/mesh_logical/MeshLogicalFactory.hh, src/mesh/mesh_logical/test/demo_mesh.cc, src/mesh/mesh_logical/test/demo_mesh.hh, src/mesh/mesh_logical/test/demo_mesh.xml, src/mesh/mesh_logical/test/test_mesh_logical.cc
Merged logical mesh changes from 0.88 to the master branch. We pushed our logical mesh changes to 0.88 but not to the master branch. So "master" needs to be updated before any future release.
=> Logical mesh merge

doc/input_spec/AmanziNativeSpecV8.rst, src/common/interface_platform/InputConverterU_State.cc, src/mpc/test/mpc_benchmark_single.xml, src/state/independent_variable_field_evaluator_fromfile.cc
Changes DoFs in a few places, including documentation, into the Amanzi-standard
closes #393
=> changes DoFs --> dofs

src/mesh/MeshCache.cc, src/mesh/MeshCache.hh
=> Adding MeshCache

src/pks/chemistry/Alquimia_PK.cc, src/pks/chemistry/Alquimia_PK.hh, src/pks/chemistry/Chemistry_PK.cc
This reduces run time of 2D F-Area simulation 5+ times by optimizing data copy in chemistry.
=> Recuding cost of data copy in Alquimia

config/SuperBuild/TPLVersions.cmake, config/SuperBuild/include/Build_Trilinos.cmake
- Problem of linking MueLu preconditioner
=> Correcting Trilinos for MueLu in SuperBuild

src/pks/chemistry/Alquimia_PK.cc, src/pks/chemistry/Amanzi_PK.cc, src/pks/chemistry/Chemistry_PK.cc, src/pks/chemistry/Chemistry_PK.hh, src/pks/transport/TransportBoundaryFunction_Alquimia.hh, src/pks/transport/TransportSourceFunction_Alquimia.hh, src/state/State.cc, src/state/State.hh
The major purpose of this pull request is to add the capability to initialize copies of the fields properly.
There is a bug during the restart when the main field and its copies are not equal to each other after the restart procedure.
There are also fixes for alquimia BC and source functions to be able to distinguish them from others.
Moreove, Alquimia update is not called if there is no water in a cell.
=> Initialization of copies. 

src/pks/chemistry/Chemistry_PK.cc, src/state/State.cc
changes to state and chemistry pk to simulate sorption in the subgrid (hyporheic zone) which uses domain sets.
=> domain_set_sorption

src/pks/shallow_water/CMakeLists.txt, src/pks/shallow_water/ShallowWater_PK.cc, src/pks/shallow_water/ShallowWater_PK.hh, src/pks/shallow_water/test/shallow_water_1D.xml, src/pks/shallow_water/test/shallow_water_2D_smooth.xml, src/pks/shallow_water/test/shallow_water_lake_at_rest.cc, src/pks/shallow_water/test/shallow_water_lake_at_rest.xml
Added lake at rest equilibrium test compatible with polygonal meshes.
=> Bathymetry test

src/pks/shallow_water/ShallowWater_PK.cc
Additional efficiency is achieved by solving Riemann problem only once. This requires to loop over faces instead of cells.
=> Switched to face-based flux assembly

src/mesh/Mesh_Algorithms.cc, src/mesh/Mesh_Algorithms.hh, src/mpc/WalkaboutCheckpoint.cc, src/operators/PDE_DiffusionNLFV.cc, src/operators/PDE_DiffusionNLFVwithBndFaces.cc, src/operators/UpwindDivK.hh, src/operators/UpwindSecondOrder.cc, src/pks/flow/Darcy_PK.cc, src/whetstone/WhetStoneMeshUtils.hh
I relocated a few whetstone functions to mesh algorithms. Have no strong opinion on the remaining. They are used only inside WhetStone.
=> Relocates generic capabilities to mesh algorithms

src/pks/PK_MixinLeaf.hh, src/solvers/InverseFactory.hh, src/state/State.cc, src/state/State.hh, src/state/evaluator/Evaluator_OperatorApply.cc, src/state/evaluator/Evaluator_OperatorApply.hh, src/utils/Key.cc, src/utils/Key.hh
Updates Key utilities to master
Adds GetEvaluatorList() back to State from master
Some PK documentation and cleanup.  See more in corresponding ATS PR
=> cleanup of names, docstrings.  Brings a few concepts back from master

config/SuperBuild/templates/pflotran-program.patch
This patch enables inhibition of the cybernetic rate due to depletion of NH4+.
=> added update to cybernetic model to pflotran patch

Docker/Dockerfile-ATS, bootstrap.sh
This updates bootstrap to accept a flag "--branch_ats_tests" and updates Docker to provide that flag.
=> updates CI to try and get testing to work when all of ATS and ats-reg-tests are on a branch

src/pks/PK_Utils.cc
Minor changes to time step manager
=> Minor changes to time step manager

src/pks/shallow_water/ShallowWater_PK.cc, src/pks/shallow_water/ShallowWater_PK.hh, src/pks/shallow_water/ShallowWater_TI.cc, src/pks/shallow_water/test/shallow_water_dry_bed.cc, src/pks/shallow_water/test/shallow_water_dry_bed.xml
Updated the algorithm for positivity correction for _fully flooded cells_ by scaling the gradient accordingly. The new implementation ensures mass conservation.
=> Sw positivity

config/SuperBuild/include/Build_PETSc.cmake
Force PETSc to search for zlib in TPLs.
=> Narrow down PETSc search

src/mesh/MeshCache_impl.hh, src/mesh/Mesh_Algorithms.cc
I only tested this on transport_* tests -- all of those tests pass.  I have not run the full suite yet to see whether it fixes other problems or (worse) introduces new bugs...
=> fixes face normal problems

config/SuperBuild/include/Build_Alquimia.cmake, config/SuperBuild/templates/alquimia-undefined_ierr.patch
need to add PR to Alquimia -- for now patch and PR to see if this fixes ATS
=> patches Alquimia to fix undefined ierr

src/pks/energy/Energy_PK.cc, src/pks/energy/IEMEvaluator.cc, src/pks/energy/IEMEvaluator.hh, src/pks/energy/TCMEvaluator_OnePhase.cc, src/pks/energy/TCMEvaluator_OnePhase.hh, src/pks/flow/Darcy_PK.cc, src/pks/flow/Flow_PK.cc, src/pks/flow/Richards_PK.cc, src/pks/mpc_pk/FlowEnergy_PK.cc, src/pks/mpc_pk/FlowMatrixFracture_PK.cc, src/pks/transport/Transport_PK.cc, src/state/IO.cc, src/state/data/RecordSet.hh, src/state/evaluators/EvaluatorMultiplicativeReciprocal.cc, src/state/evaluators/EvaluatorMultiplicativeReciprocal.hh, src/state/evaluators/EvaluatorSecondaryMonotype.hh, src/utils/Units.cc, src/utils/Units.hh, src/utils/test/utils_units.cc
Changed definition of units in RecordSet to std::string. Added units output in statistics. Added optional additional compatibility hook for units and tested with in one evaluator used in Amanzi.
=> More work on units

Docker/Dockerfile-TPLs, Docker/deploy-tpls-docker.sh
Modifies dockerfile and deploy script for TPLs to allow for manual compilation of openmpi or mpich.
=> Modify dockerfile and deploy scripts for custom built mpi

src/data_structures/TreeVector.cc, src/data_structures/TreeVector.hh, src/data_structures/TreeVectorSpace.cc, src/data_structures/TreeVectorSpace.hh, src/data_structures/TreeVector_Utils.hh, src/utils/Iterators.hh
The fix is a bit hacky, but seems to work for this purpose. refs #561
=> removes boost iterator_adaptor

doc/user_guide/capabilities/chemistry.rst, doc/user_guide/input/chemistry.rst
Adds another place where the link is dead.  Thanks for the fix @jsta
=> chemistry link fixes

src/data_structures/TreeVector.hh, src/data_structures/TreeVectorSpace.hh, src/mesh/mesh_factory/MeshFrameworkFactory.cc, src/solvers/CMakeLists.txt, src/solvers/LineSearchFunctor.hh, src/solvers/SolverFactory.cc, src/solvers/SolverLS.hh, src/solvers/SolverNKA_LS.hh, src/solvers/SolverNKA_LS_ATS.hh, src/solvers/test/solver_nonlinear.cc, src/state/Debugger.cc, src/state/Debugger.hh, src/state/evaluators/EvaluatorIndependentFunction.hh, src/utils/CMakeLists.txt, src/utils/Formatter.cc, src/utils/Formatter.hh, src/utils/test/utils_formatter.cc
- removes format usage in Debugger
- removes boost minimization algorithm in favor of new Utils::findMinimaBrent -- solver_nka test passes
- moves ATS pointer to commit that does the same in ATS
=> boost removal -- removes last boost usages from Amanzi and ATS

src/pks/CMakeLists.txt, src/pks/PK_DomainFunction.hh, src/pks/PK_DomainFunctionCoupling.hh, src/pks/PK_DomainFunctionFactory.hh, src/pks/PK_DomainFunctionField.hh, src/pks/PK_DomainFunctionFirstOrderExchange.hh, src/pks/PK_DomainFunctionSimple.hh, src/pks/PK_DomainFunctionSimpleWell.hh, src/pks/PK_DomainFunctionSubgrid.hh, src/pks/PK_DomainFunctionSubgridReturn.hh, src/pks/PK_DomainFunctionVolume.hh, src/pks/PK_DomainFunctionVolumeFraction.hh, src/pks/PK_DomainFunctionWeight.hh, src/pks/PK_DomainFunctionWeightField.hh, src/pks/PKsDefs.hh, src/pks/chemistry/Chemistry_PK.hh, src/pks/flow/Darcy_PK.cc, src/pks/flow/FlowSourceFunction.hh, src/pks/mechanics/MechanicsElasticity_PK.cc, src/pks/mpc_pk/MechanicsFlow_PK.cc, src/pks/transport/TransportBoundaryFunction_Alquimia.cc, src/pks/transport/TransportBoundaryFunction_Alquimia.hh, src/pks/transport/TransportDomainFunction.hh, src/pks/transport/TransportSourceFunction_Alquimia.cc, src/pks/transport/TransportSourceFunction_Alquimia.hh, src/pks/transport/Transport_PK.cc, src/state/State.hh, src/utils/Key.cc, src/whetstone/MFD3D_BernardiRaugelGradDiv.hh, src/whetstone/MFD3D_ElasticityGradDiv.cc
Renamed name() to getName() and added getType() which returns enum value.
=> Changed naming conventions in PK domain functions

src/operators/UpwindFlux.cc
Vandelay vector has no ghosted values.
=> A workaround for non-ghosted Vandelay vectors

src/data_structures/CompositeVector.cc, src/data_structures/CompositeVector.hh, src/data_structures/test/data_structures_composite_vector.cc, src/data_structures/test/data_structures_vandelay.cc, src/mesh/MeshMaps.cc, src/mesh/MeshMaps.hh, src/mesh/test/geometry_harnesses.hh
also adds better testing of scattering boundary_faces
=> fixes bug in vandelay vector being hard-coded as only-owned

src/solvers/PreconditionerHypre.hh
- Add destructors for Vector and Matrix for AMS.
=> Fix for hypre AMS memory

src/operators/Operator.cc, src/operators/PDE_DiffusionFV.cc, src/state/evaluators/EvaluatorSecondaryMonotype.cc, src/state/evaluators/EvaluatorSecondaryMonotype.hh
FV failed to correctly consider upwinding in the analytic Jacobian term.
=> Minimal fix for Jacobian bug in FV

Docker/Dockerfile-ATS-build
Adds elm_api to ATS CI to add this library to CI container
=> add elm api to ATS CI

Docker/Dockerfile-ATS-build
#877 had the wrong argument in bootstrap, fixing here.
=> Correct bad bootstrap argument in ATS CI update

src/mesh/MeshSets.cc, src/mesh/test/set_harnesses.hh, src/pks/flow/test/flow_richards_3D.cc
An old test was activated to test this capability. Other applications include MSTK modifications of mesh topology with subsequent manual creation of face-sets.
=> Extracts nodes from a enumerated set

src/geometry/GeometryDefs.hh, src/geometry/RegionLogical.cc, src/mesh/MeshDefs.hh, src/mesh/MeshSets.cc, src/mesh/MeshSets.hh, src/mesh/test/hex_3x3x3.xml, src/mesh/test/mesh_sets.cc, src/mesh/test/set_harnesses.hh
Boundary of a region is a topological operation which combines the closure and complement operations. However, t is implemented using mesh logic rather than set logic.
=> Added a new logical operation: boundary
