amanzi/amanzi

src/mesh/Mesh.cc, src/mesh/Mesh.hh, src/mesh/mesh_logical/MeshEmbeddedLogical.cc, src/mesh/mesh_logical/MeshEmbeddedLogical.hh, src/mesh/mesh_logical/MeshLogical.cc, src/mesh/mesh_logical/MeshLogical.hh, src/mesh/mesh_mstk/Mesh_MSTK.cc, src/mesh/mesh_mstk/Mesh_MSTK.hh, src/mesh/mesh_mstk/test/test_edges_4P.cc, src/mesh/mesh_mstk/test/test_nonmanifold_surfaces.cc
The primary changes here are to allow for non-manifold surfaces where multiple surfaces may intersect along an edge in 3-space. This requires that "faces" be allowed to connect to more than 2 "cells".
Bundled in (should have been separate) is the fix to avoid inheriting labeled sets from which surface meshes are extracted
=> Changes to allow faces to be connected to more than 2 cells

doc/input_spec/AmanziNativeSpecV7.rst, src/mesh/mesh_mstk/CMakeLists.txt, src/mesh/mesh_mstk/Mesh_MSTK.cc, src/mesh/mesh_mstk/test/hex_3x3x3.xml, src/mesh/mesh_mstk/test/hex_3x3x3_4P.xml, src/mesh/mesh_mstk/test/test_hex_3x3x3_sets.cc, src/mesh/mesh_mstk/test/test_hex_3x3x3_sets_4P.cc
I spent some time trying to find how this was implemented, as I'm fairly sure it was at some point.  Maybe in MSTK proper?  Even if it is implemented there, I think this is the better strategy.
The RegionType::ALL was introduced a while ago to allow MeshLogical to use regions effectively.  This adds support for this region type to Mesh_MSTK in addition to MeshLogical.
I like the semantics of this because it requires the user to still specify the region, with a "region: all" type.  This means there is no "magic name" to remember (or worse, mistakenly use that name to refer to a different region type).
=> adds support to Mesh_MSTK for RegionType::ALL, and tests in serial and parallel

src/data_structures/SuperMap.cc, src/data_structures/SuperMap.hh, src/operators/Operator.cc, src/operators/Operator.hh, src/operators/PDE_DiffusionMFD.cc, src/operators/TreeOperator.cc, src/operators/TreeOperator.hh, src/solvers/PreconditionerBoomerAMG.cc, src/solvers/PreconditionerBoomerAMG.hh
Hypre has a "systems" of equations approach in which, through a variety of flags, one can specify to coarsen the operator not as a single set of unknowns, but independently or collectively as block systems of equations.  This is critical in cases where scaling between the systems is not perfect or nondimensional.  Previously we allowed this through the "number of functions" option in PreconditionerBoomerAMG -- this specified a fixed, strided block operator structure where, for instance, if there were 2 "functions", then structure was assumed to be "1,2,1,2,1,2..." for each unknown.  
Unfortunately, while straightforward, this approach did not allow splitting face and cell unknowns for independent coarsening.  This pull request automates the generation of a "block index" array, which can …
=> better enables "systems" in Hypre BoomerAMG

doc/input_spec/AmanziNativeSpecV7.rst, src/common/interface_platform/InputConverterU_Flow.cc, src/common/interface_platform/InputConverterU_Transport.cc, src/common/interface_platform/test/converter_u_test3.xml, src/common/interface_platform/test/converter_u_validate3.xml, src/pks/PK_DomainFunctionSimpleWell.hh, src/pks/flow/Flow_PK.cc, src/pks/flow/test/flow_darcy_1well_peaceman_3D.xml, src/pks/flow/test/flow_darcy_well.cc
This adds Peaceman model to spec 2.3. The model is converted to flow source "simple well" with submodel "bhp" (bottom hole pressure). Spec 2.3 introduces new  element <peaceman_well/> under liquid components of sources with standard attributes "function", "start" [s], "end" [s], "value" [Pa], and two new attributes "radius" [m] and "depth" [m]. Spec example can be also found in XML file converter_u_test3.xml
=> Added Peaceman model to converter

src/mesh/Mesh.cc, src/mesh/Mesh.hh, src/mesh/mesh_logical/MeshEmbeddedLogical.cc, src/mesh/mesh_logical/MeshEmbeddedLogical.hh, src/mesh/mesh_logical/MeshLogical.cc, src/mesh/mesh_logical/MeshLogical.hh
Modified face_cell_ids_ to store cell ID or 1s complement of cell ID to indicate if face normal points out of or into the cell respectively. This allows the face_normal code to be much simpler.
@ecoon This required changes to MeshLogical and MeshEmbeddedLogical - please look over carefully before merging.
=> Simplify face_normal code

.gitmodules, bootstrap.sh, src/CMakeLists.txt, src/physics/CMakeLists.txt, src/pks/CMakeLists.txt, src/pks/mpc_pk/CMakeLists.txt, src/utils/Factory.hh, tools/cmake/AmanziOptions.cmake
This allows ATS to be directly downloaded from Amanzi:
```
git submodule update --init --remote
```
and then installed via bootstrap:
```
bootstrap.sh ... --disable-physics --enable-ats
```
=> Adds ATS as a submodule for direct compilation within Amanzi

src/mesh/CMakeLists.txt, src/mesh/DomainSet.cc, src/mesh/DomainSet.hh, src/pks/PK_Factory.cc, src/state/State.cc, src/state/State.hh, src/utils/Key.hh
This formalizes a DomainSet, a collection of small meshes on which PKs and Evaluators can be named.
It also adds support for these in factories, both in State (for evaluators) and PK_Factory (for PKs) so that users can supply things like "column_*-water_content" evaluator parameters, which will then be instantiated on "column_0-water_content", "column_1-water_content" ... where * is the global ID of an indexing set on an indexing mesh (e.g. cells on the surface mesh in this case).
This provides better support and formalization for things like ATS's Arctic intermediate scale model.
=> Domain sets are a collection of small meshes

src/state/Checkpoint.cc, src/state/State.cc
Fields read from checkpoint are marked as changed to initiate a potential update of secondary fields.
=> fixed restart issue related to overwriting pk initial conditions

src/common/interface_platform/InputConverterU_State.cc, src/common/interface_platform/test/converter_u_validate4.xml, src/common/interface_platform/test/converter_u_validate5.xml, src/common/interface_platform/test/converter_u_validate6.xml, src/common/interface_platform/test/converter_u_validate7.xml, src/common/interface_platform/test/converter_u_validate8.xml, src/mesh_functions/CompositeVectorFunctionFactory.cc, src/mesh_functions/CompositeVectorFunctionFactory.hh
It takes a lot of effort (e.g. in a converter) to figure out which components of a field have to be populated at time zero. But it is easy to say - initialize all components. This PR adds support for component(s) named "*".
=> Mask-based initialization of all components in a CV

config/SuperBuild/include/Build_Trilinos.cmake
- Ifpack2 is needed for its interface to Hypre (even if their current interface is very slow)
=> Fix hypre build

config/SuperBuild/templates/trilinos-ifpack.patch
- Add patch to fix the CopyTpetraToHypre function from Ifpack2. 
- This will allow to remove the ifpack2 interface from Amanzi in tpetra-solvers branch.
=> Fix CopyTpetraToHypre

src/mesh/mesh_extracted/MeshColumn.cc, src/mesh/mesh_extracted/MeshColumn.hh, src/mesh/mesh_extracted/MeshSurfaceCell.cc, src/mesh/mesh_factory/MeshFactory.cc
Previously, extracted meshes were contructed, by default, with the
parent mesh's comm.  This changes that default to instead construct
with the comm provided in the factory's constructor, which is the same
for all other mesh types.
This is necessary because it allows the user to pass in MPI_COMM_SELF
or other communicators if either the MeshFactory::create() call is not
collective and/or if the meshes are intended to be constructed
serially (e.g. for column mesh extraction).
Note, the old behavior can be recovered by using the same factory to
create the parent mesh and the child mesh, or construct the child
mesh's factory with the parent mesh's communicator.
This does not effect the export option "create subcommunicator" which
uses MPI_Comm_split to create a subcommunicator of the …
=> Changes the default COMM in extracted meshes

src/state/VisualizationDomainSet.cc, src/state/VisualizationDomainSet.hh, src/utils/CMakeLists.txt, src/utils/StringReducer.hh, src/utils/test/Main.cc, src/utils/test/utils_keys.cc, src/utils/test/utils_reducer.cc
Since DomainSets lift variables to visualize on the shared mesh from
which they were constructed, while observations can be done on
individual domains in a domain set, there can be cases where there is
a variable that exists on a single domain (e.g. column:0) but not on
ALL column:*.  The result of that is that the list of "lifted" vectors
is different on different ranks, and VisDomainSet hangs.
Figuring out which vectors exist on all ranks is not trivial --
effectively we have to take the intersection (across ranks) of lists
of variable names.  This is done through a new utility StringReducer
which both does MPI_Allreduce() on strings and provides a nicer
interface to do this intersection.  Tests added.
=> Adds check on VisualizationDomainSets to ensure same variables are visualized across all ranks

bootstrap.sh, config/SuperBuild/include/Build_SEACAS.cmake, config/SuperBuild/include/Build_Trilinos.cmake
This just passes PYTHON_EXECUTABLE, provided via --with-python argument to bootstrap, into Trilinos and SEACAS.
refs #652  but does not try to fix that.
=> passes python executable provided in bootstrap to a few TPLs

src/data_structures/CompositeVector.cc, src/data_structures/CompositeVectorSpace.cc, src/operators/PDE_DiffusionFV.cc
fixes some logic about communication, removes some unnecessary communication, and asserts that communication can happen when it is requested
- ASSERTS when Scatter is called but vector !ghosted
- PDE_DiffusionFV had unnecessary/unused communication
- adds some missing communication that previously relied on the user to have already done
Note that this may mean that Amanzi can remove some Scatter() calls?
=> fixes some logic on communication

src/state/State.cc, src/state/data/Record.cc, src/state/data/Record.hh, src/state/data/RecordSet.cc, src/state/data/RecordSet.hh
Initialization is enforced in one place only, when we read initial conditions in State. Amanzi "initialize" rule allows to overwrite data using state->initial condition list.
=> Optional parameter for initialization logic

src/data_structures/CompositeVector.cc, src/data_structures/CompositeVector.hh
If a face  component is based on a BlockMap, then the mesh exterior face map cannot be used. My suggestion is to create a  local importer which takes into account different number of DOFs on interior mesh faces to create an optional new importer.
=> Support of vandelay vector for non-uniform face-components

src/functions/Function.hh, src/functions/FunctionBilinearAndTime.cc, src/functions/FunctionBilinearAndTime.hh, src/functions/FunctionFactory.cc, src/functions/FunctionTabular.cc, src/functions/FunctionTabular.hh, src/functions/test/AllFunctionTest.cc
This allows the time part to be piecewise constant, instead of just linear, and matches the concepts in fuction-tabular.  Like function-tabular, values on the interval match the left endpoint of the interval.
Note only a single "forms" string is allowed -- forms may not be prescribed by interval, since this would require reading strings from the file.
Tests added to test the capability.
=> adds option for providing a form to bilinear-and-time function

src/data_structures/CompositeVectorSpace.cc
One use case of this change in a multistage simulation: 
pressure (cell + face) on stage 1 
pressure (cell + boundary_face) on stage 2.
=> Update to SubsetOf

src/data_structures/CompositeVector.cc
A boundary face_component created on a fly is not ghosted. However, field in the other state may be ghosted. This leads to different sizes of Epetra_MultiVectors in a state-based initialization.
=> Fixed paralell copy of boundary_face component

src/mesh/mesh_mstk/Mesh_MSTK.cc
fixes bug in Mesh_MSTK where enumerated GIDs were not incremented prior to comparison to MSTK GIDs, which are 1-based.
Note this requires an ATS PR as well, which fixes the test that checked this capability.
=> fixes bug in Mesh_MSTK w.r.t. enumerated set regions

config/SuperBuild/include/Build_Alquimia.cmake, config/SuperBuild/templates/alquimia-clang-void.patch
Apparently it has never been valid C to declare an empty function:
void my_function() {}
instead one must use:
void my_function(void) {}
https://stackoverflow.com/questions/41803937/func-vs-funcvoid-in-c99
Apparently no one cares except clang decided to start caring, and now this errors.  Note this is fixed in newer versions of Alquimia (I submitted a PR there).
=> clang has become the C standard police -- patch alquimia to fix empty function declarations

Docker/Dockerfile-ATS-build, src/data_structures/CompositeVector.cc, src/data_structures/CompositeVector.hh, src/functions/Function.hh, src/functions/FunctionStandardMath.hh, src/mesh_functions/ColumnMeshFunction.hh, src/operators/Operator.hh, src/solvers/CMakeLists.txt, src/solvers/IterativeMethodBelos.hh, src/solvers/PreconditionerIfpack.hh, src/solvers/ResidualDebugger.cc, src/solvers/ResidualDebugger.hh, src/state/IO.cc, src/state/IO.hh, src/state/State.cc, src/state/State.hh, src/state/evaluators/EvaluatorSecondary.cc, src/state/evaluators/EvaluatorSecondary.hh, src/state/evaluators/EvaluatorSecondaryMonotypeFromFunction.cc, src/time_integration/BDF1_TI.hh, src/utils/VerboseObject.hh, tools/amanzi_xml/amanzi_xml/common/parameter.py, tools/amanzi_xml/amanzi_xml/common/parameter_list.py
This change of IsDifferentiableWRT allows evaluators to have the key as a dependency, but NOT be differentiable with respect to that dependency.  This allows other evaluators to overload this method and turn derivatives off if they are not implemented, rather than set the derivative to zero (which results in the same answer but at the cost of doing work and then multiplying it by zero).
=> better definition of IsDifferentiableWRT

.github/workflows/amanzi-ci.yml
Fix warnings on amanzi-ci due to deprecated node-js, marketplace actions, and GitHub actions environment variable model.
=> Fix warnings on amanzi-ci.yml

Docker/Dockerfile-TPLs, Docker/deploy-tpls-docker.sh, config/SuperBuild/templates/ccse-arm64.patch
Updates dockerfile for TPLs to automatically build mpich from source with custom options that dramatically speeds running of tests on github actions when test oversubscribes runners. Refs #773.
Benefits to CI require that a new TPL image with newly compiled mpich is pushed to dockerhub and picked up by future CI runs.
=> Update Dockerfile-TPLs to manually compile mpich

.github/workflows/amanzi-ci.yml, Docker/Dockerfile-Amanzi-build, bootstrap.sh, tools/cmake/CCSEOptions.cmake
Splits ctest suite across three runners to reduce CI run times. Most recent CI run for this reduced time from ~2h7m to 1h7m, but compile time was unusually fast and so times closer to 1h30m should more often be expected.
Refs #773
=> Split ctest suite across multiple runners

Docker/Dockerfile-TPLs
Ubuntu 20 deprecated next year, moving to ubuntu 22 to stay ahead.
Also means that gcc/gfortran are newer versions based on precompiled
defaults. Also makes a few changes to shrink docker image size.
Closes [778](https://github.com/amanzi/amanzi/issues/778) and closes [765](https://github.com/amanzi/amanzi/issues/765).
=> Complete transition from ubuntu 20 to 22.

src/mesh_functions/BoundaryFunction.hh, src/mesh_functions/UniqueMeshFunction.cc, src/mesh_functions/UniqueMeshFunction.hh, src/pks/PK_DomainFunctionFactory.hh, src/pks/PK_DomainFunctionField.hh, src/pks/PK_DomainFunctionFirstOrderExchange.hh, src/pks/PK_DomainFunctionSimple.hh, src/pks/PK_DomainFunctionSimpleWell.hh, src/pks/PK_DomainFunctionSubgridReturn.hh, src/pks/PK_DomainFunctionVolume.hh, src/pks/PK_DomainFunctionWeight.hh, src/pks/energy/Energy_PK.cc, src/pks/flow/Flow_PK.cc, src/pks/mechanics/MechanicsElasticity_PK.cc, src/pks/multiphase/Multiphase_PK.cc, src/pks/navier_stokes/NavierStokes_PK.cc, src/pks/shallow_water/ShallowWater_PK.cc, src/pks/transport/Transport_PK.cc
This is required because UniqueMeshFunction is used on source terms, and those source terms are only well posed on OWNED entities when they are derived from subgrid meshes that are only instantiated on OWNED entities.
This may break some things -- run tests and confirm please CI.  If it doesn't break things, check with @lipnikov as to whether he is ok with this change.
=> Changes UniqueMeshFunction to instantiate only on OWNED entities

Docker/Dockerfile-TPLs
Modifies permissions in TPLs dockerfile given to
/home/amanzi_user directory to allow access to
binaries while running on shifter @ NERSC.
Ref #787 - and may resolve this issue.
=> Fix shifter permissions for /home/amanzi_user

src/time_integration/BDF1_TI.hh, src/time_integration/SolutionHistory.hh, src/time_integration/TimestepControllerFactory.hh, src/time_integration/TimestepControllerSmarter.cc, src/utils/Key.cc
Removing spaces from some names for checkpoint/vis, removes use of PK name as a tag, which is inconsistent with how tags are used everywhere else.
=> cleans up a few names in writing checkpoint/vis files; stops use of pk name in tag

src/utils/Key.cc, src/utils/Key.hh, src/utils/VerboseObject.cc
Minor tweak, shouldn't break anything, but allows Evaluators to read Tags of their dependencies as well as the variable name.
For an example usage, we would like to explicitly lag the dependency of water density as a function of salinity concentration in a coupled flow and transport run.  Density at the new time (Tag::NEXT) is a function of TCC at the old time (Tag::CURRENT) in this situation.  This is currently not possible because the density eos_evaluator hard-codes that my_key_'s Tag is the same as all dependency Tags.  This allows the evaluator to read the parameter list to change that tag from the default.  Note that the required change to the input file is to write the tag in the input file of the EOS evaluator -- ideally an MPC would do this automatically.
=> adds ability to read a Tag via readKey()

config/SuperBuild/CMakeLists.txt, src/common/standalone_simulation_coordinator/Main.cc
In AMANZI_TPLS version file, it's better to rename AMANZI to AMANZI_TPLS, because it's actually TPLS version rather than AMANZI version.
=> Fix on confusing versions between AMANZI_TPLS and AMANZI.

config/SuperBuild/include/Build_NetCDF_Fortran.cmake, config/SuperBuild/templates/netcdf-fortran-4.5.4-cmake.patch
When using CMake to build NetCDF-Fortran, there appears 2 unknown libraries called 'MPI::MPI_Fortran' and 'netcdff_c', which actually could not be found anywhere.
=> netcdf-fortran cmake fixes

src/mesh/MeshCache_impl.hh, src/mesh/MeshInternals_impl.hh, src/mesh/MeshSets.cc, src/mesh/SingleFaceMesh.hh, src/mesh/mesh_extracted/MeshExtractedManifold.cc, src/mesh/mesh_logical/MeshLogical.cc, src/mesh/mesh_mstk/Mesh_MSTK.cc, src/operators/PDE_DiffusionFVonManifolds.hh, src/operators/test/operator_diffusion_dfn_fv.cc, src/pks/PK_DomainFunctionSubgridReturn.hh, src/utils/ViewUtils.hh
- removes many Kokkos::resize() in favor of Kokkos::realloc(), which is significantly faster if you don't need to keep the old data
- avoids deep_copyies on host when a loop would suffice
- avoids deep_copies when subviews would suffice
- tries to take advantage of move semantics in View::operator=.  Not sure if this is significant, but since a move operator= is defined, we should use it where possible.
=> work to optimize use of View in mesh construction/caching

src/mpc/test/mpc_multiphase_fractures.cc, src/operators/PDE_AdvectionUpwindDFN.cc, src/operators/PDE_DiffusionFVonManifolds.cc, src/operators/UpwindFluxManifolds.cc, src/pks/multiphase/Multiphase_PK.cc, src/pks/multiphase/Multiphase_PK.hh, src/pks/multiphase/Multiphase_TI.cc
Added a temporary parameter to turn off the failing block. The default behavior is to use this block
=> Work around a failing block in the preconditioner for multiphase PK

config/SuperBuild/TPLVersions.cmake, config/SuperBuild/include/Build_Trilinos.cmake
We used to need a specific hash of Trilinos -- currently we are using Trilinos 15.1.0.
When we stopped using the old hash, I must have missed that changing the version wasn't enough -- because we provided a GIT_REPOSITORY but not a GIT_HASH, we were likely getting the current master of Trilinos.
This changes Build_Trilinos to use the release version, not current master.
=> fixes bug in how we download Trilinos -- use release not git

bootstrap.sh
Adds the "--elm_ats_api" flag to bootstrap to optionally turn on building the ATS interface to ELM. Default false.
=> add elm_ats_api build option to boostrap

bootstrap.sh
Removes BUILD_ELM_ATS_API flag from bootstrap following comment from @lipnikov on #848. 
(Apologies for the double PR - the one I had opened a few minutes ago had been from a stale branch).
=> remove BUILD_ELM_ATS_API flag entirely from bootstrap

src/mpc/CycleDriver.cc, src/pks/CMakeLists.txt, src/pks/PK.hh, src/pks/PK_Physical.hh, src/pks/chemistry/Alquimia_PK.cc, src/pks/chemistry/Alquimia_PK.hh, src/pks/chemistry/Chemistry_PK.cc, src/pks/chemistry/Chemistry_PK.hh, src/pks/chemistry/test/chemistry_alquimia_pk.cc, src/pks/chemistry/test/chemistry_amanzi_pk.cc, src/pks/mpc_pk/EnergyMatrixFracture_PK.cc, src/state/CMakeLists.txt, src/state/State.cc, src/state/state_evaluators_registration.hh, src/state/test/state_dag.cc
This creates another level of setup, called parseParameterList(), that occurs after PK construction but before Setup. Most ATS PKs constructor contents are now moved into parseParameterList(), and all PKs are modified to have them set their primary variables in this call. This allows the key advancement that calling State::SetEvaluator(key, tag, eval) (the function that is called inside of RequireEvaluator(...) after construction) can now call eval->EnsureEvaluators(). This means that the DAG is now valid as soon as the evaluator is set. This allows some important changes to the use of the dag, e.g. calling Evaluator::IsDifferentiableWRT() immediately after calling RequireEvaluator().
This closes #654  and is an important step toward #646
=> Rework of PKs to split out parseParameterList, make SetEvaluator() call EnsureEvaluators()

.github/workflows/amanzi-ci.yml
docker-login action v2 is issuing warnings about
node.js deprecation. bumping to v3 to remove warning
=> bump docker-login action version

src/data_structures/CompositeVector.cc, src/data_structures/CompositeVector.hh, src/data_structures/CompositeVectorSpace.hh, src/data_structures/test/data_structures_vandelay.cc, src/operators/UpwindDivK.hh, src/operators/UpwindFlux.cc, src/operators/UpwindFluxManifolds.cc, src/operators/UpwindGravity.cc, src/operators/UpwindSecondOrder.cc, src/operators/test/operator_coupled_diffusion.cc, src/operators/test/operator_diffusion_convergence.cc, src/state/Debugger.cc
Previously, if A & B are CVs,
A.Update(1, B, 1)
where A.HasComponent("boundary_face") and B.HasComponent("face") would
do nothing, because !B.HasComponent("boundary_face").  This should be
allowed, however, because B.ViewComponent("boundary_face") uses the
Vandelay map and all is fine.
This commit makes the logic:
A.HasComponent(comp) <-- a _writable_ view of comp is available (no change)
A.ProvidesComponent(comp) <-- a _readable_ view of comp is available (new)
and uses ProvidesComponent() where possible to let Update(), Dot(),
etc work through the Vandelay map.
Note also that it is probably implied that:
!(A.HasComponent("boundary_face") && A.HasComponent("face"))
(you can't have both) though I'm not sure whether this breaks anything
or not.
Several changes to code were also made to:
if …
=> Adds CV::ProvidesComponent() and uses it in vector math

config/SuperBuild/TPLVersions.cmake
Updates TPLConfig file to deal with changes to gitlab links for TPLs (pflotran specifically). Closes https://github.com/amanzi/amanzi/issues/874.
This commit was initially also in #875 but separating out as the distutils portion of that PR requires additional testing.
=> Update pflotran md5

config/SuperBuild/templates/netcdf-fortran-4.5.4-cmake.patch
Existing netcdf-fortran 4.5.4 patch (from #735) appears to still permit `-lMPI::MPI_Fortran -lnetcdff_c` libraries to be added to `--flibs` output of nf-config in some cases.
This doesn't seem to cause any issues currently in Amanzi or ATS, but when trying to build ELM-ATS, E3SM compilation fails as nf-config is used to determine the netcdf-fortran libraries, which ends up possibly passing libraries that don't exist.
Unable to track down why the existing patch doesn't work in some situations, but this simplified patch is inspired by a change to CMakeLists.txt in Netcdf-fortran for versions > 4.5.4. (e.g., https://github.com/Unidata/netcdf-fortran/pull/322 first released in 4.6.0.)
Local test of these changes on arm Mac seems to be correct now.
=> add simplified netcdf-fortran-4.5.4 patch

config/SuperBuild/include/Build_METIS.cmake, config/SuperBuild/include/Build_ParMetis.cmake, config/SuperBuild/templates/metis-patch-step.cmake.in, config/SuperBuild/templates/metis-patch-step.sh.in, config/SuperBuild/templates/metis-realtype.patch, config/SuperBuild/templates/parmetis-patch-step.cmake.in, config/SuperBuild/templates/parmetis-patch-step.sh.in, config/SuperBuild/templates/parmetis-realtype.patch
Metis defined real_t = float. This PR defines real_t = double. Note that MSTK does allocate real_t arrays. Hence, impact is limited to ParMetis.
=> Changed default floating number to 64

src/mesh/MeshCache_decl.hh, src/mesh/MeshCache_impl.hh, src/mesh/mesh_extracted/MeshExtractedManifold.cc, src/mesh/mesh_extracted/MeshSurfaceCell.cc, src/mesh/mesh_factory/MeshFactory.cc, src/pks/PK_DomainFunctionFirstOrderExchange.hh, src/utils/VerboseObject.hh
adds
```
std::vector<std::string> Mesh::getSpaceDimensionNames()
Mesh::setSpaceDimensionNames(std::vector<std::string>)
```
By default, these get set to 'x', 'y', and (if 3D) 'z'.  The user may change them using the MeshFactory parameter list using the parameter `"space dimension names`" (e.g. for 2D x,z problems, or 1D problems).
Also changes molar_ratio to mole_fraction in a few places (cleanup) and adds more documentation to the verbosity level option description (docs).
=> Meshes gain the ability to name their dimensions

config/SuperBuild/TPLVersions.cmake
Alquimia v1.2.0 enables surface area update in the PFLOTRAN engine based on mineral volume fractions (example available in Alquimia repository batch chemistry benchmarks).
Supersedes Alquimia v1.1.1 (which was minor bug fixes) in this TPL release. 
Passes all 330 Amanzi reg tests on my machine (Ubuntu 22.04 LTS, gcc/12.2.0, openmpi/4.1.5, lapack/3.11.0)
=> updates Alquimia TPL to v1.2.0

tools/py_lib/CMakeLists.txt
This parameter defines correct variable 'base' which allows us to replace it by another value pointing to Amanzi's installation.
=> Added parameter 'scheme' to a sysconfig function

.github/workflows/build-tpls.yml
Close #909.
Allows for testing of new TPL collections through CI - existing CI runs from master with no way to specify.
=> add minimal patch for #909
